Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 1500
Metrics/BlockLength:
  Max: 50
Metrics/AbcSize:
  Max: 20
Lint/UnusedMethodArgument:
  Exclude:
    - lib/legion/extensions/sleepiq/runners/*.rb
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space
Style/SymbolArray:
  Enabled: true
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false